# Generated by Django 3.1.2 on 2021-05-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='booking_interval_minutes',
            field=models.IntegerField(default=30),
        ),
    ]
