# Generated by Django 3.1.2 on 2021-04-21 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210313_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='calendar_filter',
            new_name='sub_calendar',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Start Time'),
        ),
    ]
