# Generated by Django 3.1.2 on 2021-05-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210526_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_booking',
            field=models.BooleanField(default=False, verbose_name='Allow Booking'),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking_interval_buffer',
            field=models.IntegerField(default=0, verbose_name='Minutes Between Sessions *optional*'),
        ),
        migrations.AlterField(
            model_name='event',
            name='booking_interval_minutes',
            field=models.IntegerField(default=30, verbose_name='Session Length'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(default=False, verbose_name='Open to Public'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='open_editing',
            field=models.BooleanField(default=False, verbose_name='Public can Edit'),
        ),
    ]
