# Generated by Django 3.1.2 on 2021-04-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210421_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
    ]
