# Generated by Django 3.1.2 on 2021-06-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20210616_1154'),
        ('industries', '0002_auto_20210518_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membertoindustry',
            options={'verbose_name': 'Company Industry Relationship', 'verbose_name_plural': 'Company Industries Relationships'},
        ),
        migrations.CreateModel(
            name='UsertoIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industries.industry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberuser')),
            ],
            options={
                'verbose_name': 'User Industry Relationship',
                'verbose_name_plural': 'User Industry Relationships',
            },
        ),
    ]
