# Generated by Django 3.1.2 on 2021-05-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memberuser_is_wf_admin'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='Discussion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thread',
            new_name='discussion',
        ),
    ]
