# Generated by Django 3.1.2 on 2021-06-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210525_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='thread',
            new_name='discussion',
        ),
    ]
