# Generated by Django 3.1.2 on 2021-06-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210608_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussion',
            name='number_of_flags',
            field=models.IntegerField(default=0),
        ),
    ]
