# Generated by Django 3.1.2 on 2021-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210106_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_flags',
            field=models.IntegerField(default=0),
        ),
    ]
