# Generated by Django 3.1.2 on 2021-03-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_auto_20210224_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'verbose_name': 'Discussion', 'verbose_name_plural': 'Discussions'},
        ),
    ]
