# Generated by Django 3.1.2 on 2021-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210306_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberlikeorflagpost',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberlikeorflagpost',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberlikeorflagreply',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberlikeorflagreply',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
