# Generated by Django 3.1.2 on 2021-01-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='owner',
        ),
        migrations.AddField(
            model_name='calendar',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='CalendarOwner',
        ),
    ]
