# Generated by Django 3.1.2 on 2021-01-27 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20210124_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime.now, help_text='Day of the event', verbose_name='Day of Event'),
        ),
    ]
