# Generated by Django 3.1.2 on 2021-02-03 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20210127_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.filter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Day of Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Final time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Starting time'),
        ),
        migrations.DeleteModel(
            name='FilterToEvent',
        ),
    ]
