# Generated by Django 3.1.2 on 2021-03-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20210203_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='member',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
