# Generated by Django 3.1.2 on 2021-05-18 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210518_1905'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberSkills',
            new_name='MemberToSkills',
        ),
        migrations.RenameModel(
            old_name='MemberUserSkills',
            new_name='UserToSkills',
        ),
        migrations.AlterModelOptions(
            name='usertoskills',
            options={'verbose_name': 'User Skills', 'verbose_name_plural': 'User Skills'},
        ),
        migrations.RenameField(
            model_name='usertoskills',
            old_name='member_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='membertoskills',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
