# Generated by Django 3.1.2 on 2021-06-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20210518_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membertoskills',
            options={'verbose_name': 'Member Skill Relationship', 'verbose_name_plural': 'Member Skill Relationships'},
        ),
        migrations.AlterModelOptions(
            name='usertoskills',
            options={'verbose_name': 'User Skill Relationship', 'verbose_name_plural': 'User Skill Relationships'},
        ),
    ]
