# Generated by Django 3.1.2 on 2020-11-02 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('address_2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('business_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('cell_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('bio', models.TextField()),
                ('publicly_viewable', models.BooleanField(default=True)),
                ('membership_expiry', models.DateField()),
                ('membership_since', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('can_create_forum_group', models.BooleanField(default=False)),
                ('can_post_to_forums', models.BooleanField(default=False)),
                ('can_add_calendar_events', models.BooleanField(default=False)),
                ('can_see_all_members', models.BooleanField(default=False)),
                ('can_edit_company_profile', models.BooleanField(default=False)),
                ('can_see_company_console', models.BooleanField(default=False)),
                ('can_add_employees', models.BooleanField(default=False)),
                ('can_delete_posts', models.BooleanField(default=False)),
                ('is_account_manager', models.BooleanField(default=False)),
                ('is_calendar_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_permissions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.role')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.skill')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.company')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.company')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.industry')),
            ],
        ),
    ]
