# Generated by Django 3.1.2 on 2021-05-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberCompany',
            new_name='UserToMember',
        ),
    ]
