# Generated by Django 3.1.2 on 2021-05-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20210518_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='permissions',
            name='role_permissions',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_add_calendar_events',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_add_employees',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_create_forum_group',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_delete_posts',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_edit_company_profile',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_post_to_forums',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_see_all_members',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='can_see_company_console',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='is_account_manager',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='is_calendar_manager',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='title',
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_add_calendar_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_add_employees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_delete_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_edit_company_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='can_edit_own_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='permissions',
            name='is_member_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissions',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.permissions'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.memberuser'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserToMember',
        ),
    ]
