# Generated by Django 3.1.2 on 2021-05-19 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210519_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='permissions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.permissions'),
            preserve_default=False,
        ),
    ]
