# Generated by Django 3.1.2 on 2021-05-26 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memberuser_is_wf_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='business_email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
