# Generated by Django 3.1.2 on 2020-11-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20201117_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_since',
            field=models.DateField(),
        ),
    ]
