# Generated by Django 3.1.2 on 2021-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20201117_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='members/static/members/company_pic/'),
        ),
    ]
