# Generated by Django 3.1.2 on 2021-05-28 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20210526_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberuser',
            old_name='member',
            new_name='primary_member',
        ),
        migrations.CreateModel(
            name='UserToMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('member_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.memberuser')),
            ],
            options={
                'verbose_name': 'Member to User Relationships',
            },
        ),
    ]
