# Generated by Django 3.1.2 on 2021-04-07 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_company_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='membercompany',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.role'),
        ),
    ]
