# Generated by Django 3.1.2 on 2021-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20210528_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertomember',
            options={'verbose_name': 'Member To User Relationship', 'verbose_name_plural': 'Member to User Relationships'},
        ),
        migrations.AddField(
            model_name='usertomember',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
