# Generated by Django 3.1.2 on 2021-04-18 22:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_membercompany_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cell_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
