# Generated by Django 3.1.2 on 2021-06-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20210605_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='member',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
            preserve_default=False,
        ),
    ]
