# Generated by Django 3.1.2 on 2021-06-09 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_userrole_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='title',
            new_name='role_title',
        ),
    ]
