# Generated by Django 3.1.2 on 2021-04-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20210418_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='publicly_viewable',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
    ]
