# Generated by Django 3.1.2 on 2021-06-09 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20210609_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
            preserve_default=False,
        ),
    ]
