# Generated by Django 3.1.2 on 2021-04-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20210419_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='profile_gallery'),
        ),
        migrations.AlterField(
            model_name='member',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='profile_gallery'),
        ),
    ]
