# Generated by Django 3.1.2 on 2021-04-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20210420_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
