# Generated by Django 3.1.2 on 2021-06-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_permissions_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'User Role', 'verbose_name_plural': 'User Roles'},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='usertomember',
            unique_together={('member_user', 'member')},
        ),
    ]
