# Generated by Django 3.1.2 on 2021-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_auto_20210616_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='can_add_skills',
            field=models.BooleanField(default=False),
        ),
    ]
