# Generated by Django 3.1.2 on 2021-04-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20210421_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
